name: tontine_hub
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.10.3
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  pointycastle: ^4.0.0
  flutterwave_standard: ^1.1.0
  http: ^1.5.0
  lottie: ^3.3.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  charts_flutter: ^0.12.0
  in_app_purchase: ^3.2.3
  pdf: ^3.11.3
  mockito: ^5.5.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
